//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int id_producto { get; set; }
        public string codigo_barras { get; set; }
        public string nombre { get; set; }
        public int id_marca { get; set; }
        public int id_color { get; set; }
        public int id_talla { get; set; }
        public int id_sexo { get; set; }
        public string foto { get; set; }
        public decimal precio_venta { get; set; }
        public decimal precio_costo { get; set; }
        public int stock { get; set; }
        public bool estatus { get; set; }
        public int id_categoria { get; set; }
        public string codigo_barras_original { get; set; }
    }
}
