//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoDetalle
    {
        public int id { get; set; }
        public int id_inventario { get; set; }
        public int id_articulo { get; set; }
        public int stock_sistema { get; set; }
        public int cantidad_contada { get; set; }
        public Nullable<int> diferencia { get; set; }
    }
}
