//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioMovimientos
    {
        public int id_movimiento { get; set; }
        public string codigo_barras { get; set; }
        public string codigo_barras_original { get; set; }
        public string nombre_producto { get; set; }
        public int cantidad { get; set; }
        public string motivo { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public int stock_antes { get; set; }
        public int stock_despues { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
