//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tallas
    {
        public int id_talla { get; set; }
        public string nombre { get; set; }
    }
}
