//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id_venta { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public int cantidad_productos { get; set; }
        public decimal total { get; set; }
        public bool estatus { get; set; }
        public string forma_pago { get; set; }
        public Nullable<System.DateTime> fecha_editado { get; set; }
        public Nullable<int> id_usuario_editado { get; set; }
    }
}
